### PR TITLE
add follow mode feature and show gravatar in typing

### PR DESCRIPTION
**Pull request by gangseok514**
1. add follow mode(default is true)
2. show gravatar correctly in remote typing
3. fix infinite loop happen while "re-sync"

### CODE REVIEW

**Comment by luizbafilho** [comment]
@gangseok514 It seems you did a really good job. I'm going to validate if there are no bugs, before merge it.

**Comment by luizbafilho** [comment]
@gangseok514  Everything it's working, nice job. Before I merge it,  I would like to ask you to change the 'Enable Follow Mode' label to just 'Sync Tabs' I think it makes clearer what it does.

Thanks for the PR.

**Comment by gangseok514** [comment]
thanks!! I will change the name then request again

**Comment by gangseok514** [comment]
Hi, sorry for late. I updated code! I'm glad to contribute your package!

**Pull request merged**
